apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "installer.fullname" . }}
  labels:
    {{- include "installer.labels" . | nindent 4 }}
rules:
# krateoplatformops crd
- apiGroups:
  - krateo.io
  resources:
  - krateoplatformops
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
