{{- if not .Values.krateoplatformops.vcluster.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "installer.fullname" . }}-krateo
  labels:
    {{- include "installer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles","rolebindings","roles"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces","secrets"]
    verbs: ["create","get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create","get"]
  - apiGroups: ["widgets.ui.krateo.io"]
    resources: ["cardtemplates","formtemplates"]
    verbs: ["create","get"]
  - apiGroups: ["layout.ui.krateo.io"]
    resources: ["rows","columns"]
    verbs: ["create","get"]
  - apiGroups: ["basic.authn.krateo.io"]
    resources: ["users"]
    verbs: ["create","get"]
  - apiGroups: ["core.krateo.io"]
    resources: ["compositiondefinitions","schemadefinitions"]
    verbs: ["create","get"]
{{- end }}
