apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "installer.fullname" . }}-krateo
  labels:
    {{- include "installer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles","rolebindings","roles"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces","secrets"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["templates.krateo.io"]
    resources: ["restactions"]
    verbs: ["*"]
  - apiGroups: ["widgets.templates.krateo.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["basic.authn.krateo.io"]
    resources: ["users"]
    verbs: ["*"]
  - apiGroups: ["core.krateo.io"]
    resources: ["compositiondefinitions","schemadefinitions"]
    verbs: ["*"]
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["*"]
  - apiGroups: ["eventrouter.krateo.io"]
    resources: ["registrations"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["*"]
  {{ if and .Values.krateoplatformops.composablefinops.enabled .Values.krateoplatformops.finopscratedb.openshift }}
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["*"]
  {{ end }}