apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "installer.fullname" . }}
  labels:
    {{- include "installer.labels" . | nindent 4 }}
data:
  INSTALLER_NAMESPACE: "{{ .Release.namespace }}"
