apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "installer.fullname" . }}
  labels:
    {{- include "installer.labels" . | nindent 4 }}
data:
  INSTALLER_PROVIDER_NAMESPACE: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}