apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "installer.fullname" . }}
  labels:
    {{- include "installer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ include "installer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "installer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
