{{- if .Values.krateoplatformops.init.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "installer.fullname" . }}-starter-pack
  labels:
    {{- include "installer.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
{{- end }}
