apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "installer.fullname" . }}
  labels:
    {{- include "installer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
